//===========================================================================
// Verilog file generated by Clarity Designer    10/12/2024    18:06:22  
// Filename  : csi2_output_pkt_formatter.v                                                
// IP package: CSI-2/DSI D-PHY Transmitter 1.4                           
// Copyright(c) 2017 Lattice Semiconductor Corporation. All rights reserved. 
//===========================================================================

module csi2_output_pkt_formatter (
input  wire                       reset_n,
input  wire                       core_clk,
input  wire                 [1:0] vc_i,
input  wire                 [5:0] dt_i,
input  wire                [15:0] wc_i,
input  wire                       vsync_start_i,
input  wire                       hsync_start_i,
input  wire                       sp_en_i,
input  wire                       lp_en_i,
input  wire                 [7:0] frame_max_i,
input  wire [4*16-1:0] byte_data_i,
input  wire                       byte_data_en_i,
output wire [4*16-1:0] dphy_pkt_o,
output wire                       dphy_pkten_o,
input  wire                       d_hs_rdy_i,
output wire                       ld_pyld_o,
output wire                       pix2byte_rstn_o
);

pkt_formatter # (
  .FRAME_CNT_ENABLE ("ON"),
  .LINE_CNT_ENABLE  ("ON"),
  .EOTP_ENABLE      ("OFF"),
  .PKTHDR_FIFO_IMPL ("EBR"),
  .PKTHDR_FIFO_DEPTH(64),
  .LANE_WIDTH       (2),
  .DATA_WIDTH       (16),
  .INTF_TYPE        ("CSI2"),
  .TX_GEAR          (8),
  .CRC16            (1)
)
u_pkt_formatter (
  .reset_n          (reset_n),
  .core_clk         (core_clk),
  .vc_i             (vc_i),
  .dt_i             (dt_i),
  .wc_i             (wc_i),
  .vsync_start_i    (vsync_start_i),
  .hsync_start_i    (hsync_start_i),
  .sp_en_i          (sp_en_i),
  .lp_en_i          (lp_en_i),
  .frame_max_i      (frame_max_i),
  .byte_data_i      (byte_data_i),
  .byte_data_en_i   (byte_data_en_i),
  .dphy_pkt_o       (dphy_pkt_o),
  .dphy_pkten_o     (dphy_pkten_o),
  .d_hs_rdy_i       (d_hs_rdy_i),
  .ld_pyld_o        (ld_pyld_o),
  .pix2byte_rstn_o  (pix2byte_rstn_o)
);
endmodule


