//===========================================================================
// Verilog file generated by Clarity Designer    10/02/2024    19:54:05  
// Filename  : p2b_synchronizer_bb.v                                                
// IP package: Pixel to Byte Converter 1.3                           
// Copyright(c) 2017 Lattice Semiconductor Corporation. All rights reserved. 
//===========================================================================

module p2b_synchronizer (
  input wire rstn,
  input wire clk,
  input wire in,
  output wire out
);

endmodule // sync
