/* Verilog module instantiation template generated by SCUBA Diamond (64-bit) 3.13.0.56.2 */
/* Module Version: 5.7 */
/* Wed Oct 02 17:37:33 2024 */

/* parameterized module instance */
int_pll __ (.CLKI( ), .RST( ), .CLKOP( ), .CLKOS( ));
