//===========================================================================
// Verilog file generated by Clarity Designer    10/02/2024    19:39:36  
// Filename  : tx_dphy_tinit_count_bb.v                                                
// IP package: CSI-2/DSI D-PHY Transmitter 1.4                           
// Copyright(c) 2017 Lattice Semiconductor Corporation. All rights reserved. 
//===========================================================================

module tx_dphy_tinit_count (
input  wire clk,
input  wire resetn,
output wire tinit_done_o
);

endmodule


