//===========================================================================
// Verilog file generated by Clarity Designer    10/02/2024    19:39:36  
// Filename  : tx_dphy_tx_global_operation_bb.v                                                
// IP package: CSI-2/DSI D-PHY Transmitter 1.4                           
// Copyright(c) 2017 Lattice Semiconductor Corporation. All rights reserved. 
//===========================================================================

module tx_dphy_tx_global_operation (
input  wire                       clk_hs_en_i,
input  wire                       d_hs_en_i,
output wire                       d_hs_rdy_o,
input  wire                       reset_n,
input  wire                       core_clk,
input  wire                       dphy_pkten_i,
input  wire [4*16-1:0] dphy_pkt_i,
output wire                       hs_clk_gate_en_o,
output wire                       hs_clk_en_o,
output wire                       hs_data_en_o,
output wire   [16-1:0] hs_data_d3_o,
output wire   [16-1:0] hs_data_d2_o,
output wire   [16-1:0] hs_data_d1_o,
output wire   [16-1:0] hs_data_d0_o,
output wire                       c2d_ready_o,
output wire                       lp_clk_en_o,
output wire                       lp_clk_p_o,
output wire                       lp_clk_n_o,
output wire                       lp_data_en_o,
output wire                       lp_data_p_o,
output wire                       lp_data_n_o
);

endmodule


